Server:
  Name: golang-example
  Port: 8080

Database:
  ServerType: postgres
  DriverSource: host=db.vjlkmagqczfwmvpablpo.supabase.co port=5432 user=postgres password=SPbFuYLz42MpP3Zn dbname=postgres sslmode=disable
  MaxOpenConns: 5
  MaxIdleConns: 5
  ConnMaxLifetime: 30
  ConnMaxIdleTime: 30
