Server:
  Name: golang-example
  Port: 8080

Database:
  ServerType: postgres
  DriverSource: host=db.vjpgdoelfnmgwmpdokkn.supabase.co port=5432 user=postgres password=SuretyBond2023! dbname=Go_Example sslmode=disable
  MaxOpenConns: 5
  MaxIdleConns: 5
  ConnMaxLifetime: 30
  ConnMaxIdleTime: 30
